/**
 * Two halves of one negotiation, shaped like a Chromium offer and an SFU answer. Lines are joined
 * with CRLF as on the wire.
 */
const crlf = (lines: string[]) => lines.join('\r\n') + '\r\n';

/** Chromium offer: audio with Opus DTX + in-band FEC and RED; video VP8 + RTX sending three simulcast layers. */
export const CHROME_OFFER = crlf([
	'v=0',
	'o=- 4611731400430051336 2 IN IP4 127.0.0.1',
	's=-',
	't=0 0',
	'a=group:BUNDLE 0 1',
	'a=extmap-allow-mixed',
	'a=msid-semantic: WMS',
	'm=audio 9 UDP/TLS/RTP/SAVPF 111 63',
	'c=IN IP4 0.0.0.0',
	'a=rtcp:9 IN IP4 0.0.0.0',
	'a=ice-ufrag:abcd',
	'a=ice-pwd:supersecretpassword1234',
	'a=ice-options:trickle',
	'a=fingerprint:sha-256 AA:BB',
	'a=setup:actpass',
	'a=mid:0',
	'a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level',
	'a=sendrecv',
	'a=rtcp-mux',
	'a=rtpmap:111 opus/48000/2',
	'a=rtcp-fb:111 transport-cc',
	'a=fmtp:111 minptime=10;useinbandfec=1;usedtx=1',
	'a=rtpmap:63 red/48000/2',
	'a=fmtp:63 111/111',
	'a=ssrc:1111 cname:x',
	'm=video 9 UDP/TLS/RTP/SAVPF 96 97',
	'c=IN IP4 0.0.0.0',
	'a=ice-ufrag:abcd',
	'a=ice-pwd:supersecretpassword1234',
	'a=setup:actpass',
	'a=mid:1',
	'a=sendonly',
	'a=rtcp-mux',
	'a=rtcp-rsize',
	'a=rtpmap:96 VP8/90000',
	'a=rtcp-fb:96 goog-remb',
	'a=rtcp-fb:96 transport-cc',
	'a=rtcp-fb:96 nack',
	'a=rtcp-fb:96 nack pli',
	'a=rtpmap:97 rtx/90000',
	'a=fmtp:97 apt=96',
	'a=rid:q send',
	'a=rid:h send',
	'a=rid:f send',
	'a=simulcast:send q;h;f',
]);

/** SFU answer: ICE lite, `a=setup:passive`, Opus with FEC but no DTX, RED dropped, video received. */
export const SFU_ANSWER = crlf([
	'v=0',
	'o=mediasoup-client 10000 1 IN IP4 0.0.0.0',
	's=-',
	't=0 0',
	'a=ice-lite',
	'a=group:BUNDLE 0 1',
	'a=msid-semantic: WMS *',
	'm=audio 7 UDP/TLS/RTP/SAVPF 111',
	'c=IN IP4 127.0.0.1',
	'a=ice-ufrag:efgh',
	'a=ice-pwd:anothersecret',
	'a=setup:passive',
	'a=mid:0',
	'a=recvonly',
	'a=rtcp-mux',
	'a=rtpmap:111 opus/48000/2',
	'a=rtcp-fb:111 transport-cc',
	'a=fmtp:111 minptime=10;useinbandfec=1',
	'm=video 7 UDP/TLS/RTP/SAVPF 96 97',
	'c=IN IP4 127.0.0.1',
	'a=setup:passive',
	'a=mid:1',
	'a=recvonly',
	'a=rtcp-mux',
	'a=rtpmap:96 VP8/90000',
	'a=rtcp-fb:96 transport-cc',
	'a=rtcp-fb:96 nack',
	'a=rtpmap:97 rtx/90000',
	'a=fmtp:97 apt=96',
	'a=rid:q recv',
	'a=rid:h recv',
	'a=rid:f recv',
	'a=simulcast:recv q;h;f',
]);
